### ISSUE TITLE
 [URF.Repository.Pattern.Ef6] Package dependency of CommonServiceLocator

### ISSUE THREAD

**Issue by rdhainaut** [urfnet/URF.NET#23]
I use the Urf package v5.1.0-beta but
If the package [CommonServiceLocator] is updated to the latest version [2.0.1], I get the following error :

exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

The error is gone if I use the version [1.3.0.0] of CommonServiceLocator package.
If the version 1.3.0.0 must be used then it should be explicitely setted in the nuget dependency no ?

**Comment by lelong37** [comment]
Yes, could you be so kind to issue a pull request with v1.3.0.0 of the package explicitly set? Also, CommonServiceLocator is a dependency only because our sample uses Unity for DI & IoC, we have many teams that are using other DI & IoC frameworks and removed ServiceLocator as a whole.

**Comment by lelong37** [comment]
FYI, we may update this to the highest CommonServiceLocator dependency in our RC1 release, will update this issue, once we've made a decision, as well as communicate which version we land at.

**Comment by tonysneed** [comment]
@lelong37 Do we need to refactor code to update to CommonServiceLocator v2.x?

**Comment by lelong37** [comment]
Yes, would probably make the most sense. Although there is a big debate on usages of Service Locator, there is a large amount of teams using it with their preferred or choice of DI & IoC. In the sample we're using Unity for DI & IoC and using the Unity Service Locator implementation, however a slew of DI  & IoC frameworks out there support Service Locator, with their own implementation of Service Locator,  however, their own implementation of Service Locator are all implementing the Common Service Locator **interface**.  @tonysneed

**Comment by tonysneed** [comment]
Let's update the package for v5.1-rc.

**Comment by martinarapovic** [comment]
Hi @tonysneed & @lelong37, what do you think about solution that can completely remove dependency to Service Locator, using repository factory. For example:
```csharp
public interface IRepositoryFactory
{
    IRepositoryAsync<TEntity> Create<TEntity>() where TEntity : class, ITrackable;
}
```

Than this factory can be passed to UnitOfWork via ctor.

**Comment by lelong37** [comment]
Yes you can do this I suppose (not preferred), but doesn't play nicely with DI/IoC, we just pushed a fix for UnitOfWork.GetRepositoryAsync to work with both w/ DI/IoC (Unity) https://github.com/urfnet/URF.NET/commit/70e09dc43d669d6b7f242a63b029a92f5dd6a50d
