### ISSUE TITLE
.NET Core Version

### ISSUE THREAD

**Issue by ferryferry** [urfnet/URF.NET#36]
Hi LeLong37,

I created a light version of your implementation for .NET Core. I Already use it in a production application. 
Maybe it's helpful for others as well ? https://github.com/ferryferry/Patterns

**Comment by tonysneed** [comment]
@lelong37 Let's take inspiration from this and port to .NET Core ASAP.  It should be .NET Standard 2.x.

I think we should break it up into a Core package that is more lightweight and does not depend on Trackable Entities.  Maybe we should also break out the fluent IQueryable API as well.  That way, someone can pick up the lighter Core package and get started with very little friction.

**Comment by tonysneed** [comment]
Tracking the modularization issue with #37.

**Comment by lelong37** [comment]
@ferryferry could you be so kind to issue a PR with your .NET Core port? Would love to have this as we update URF for .NET Core, thanks!

**Comment by ferryferry** [comment]
@lelong37 Sure, I will try to finish it in one week.

**Comment by lelong37** [comment]
@ferryferry thanks and much appreciated, we're hoping to leverage your work/port as much as possible as additional prescriptive guidance.  Both URF and [Trackable Entites](https://github.com/TrackableEntities) Team will be teaming up for this effort, there will be some significant architectural and design improvements, I've updated the URF readme with a roadmap, listing what the high-level epics/milestones for .NET Core version.

**Comment by lelong37** [comment]
Hey @ferryferry, just wanted to chime in and see how things are going? We're hoping to leverage your .NET Core version of URF.

**Comment by ferryferry** [comment]
Hi @lelong37 I started with the pullrequest, however I got a little problem. Because of project version differences between the Repository.Pattern project and the Repository.Pattern.EfCore... 

The initial Repository.Pattern project is targeted at .NET Framework and the one i'm adding is pointing .NET Standard. I even tried to change the Repository.Pattern framework to .NET Standard, but then Trackable Entities kicks in with version complaints...

Do you have any tips for me?
This is what I have at the moment: 
[Solution](https://www.dropbox.com/s/jvqrp0dynk9tj65/URF.zip?dl=0
)

Maybe you can help me out?

**Comment by tonysneed** [comment]
You have to switch to TE for .NET Core, which is NET Standard 2.0.

**Comment by ferryferry** [comment]
@tonysneed and @lelong37 Today I had a lot of progress with porting the things to .NET Standard. I created a separate branch for my edits but i'm not able to push it to the repository.

Not all errors are gone.. I'm facing errors in two classes of the EF6 package. 
![image](https://user-images.githubusercontent.com/17270672/34847668-69522446-f71c-11e7-9935-c069469b8320.png)
This is because the EF6 package does still have dependencies on TrackableEntities.Common. When I only use TrackableEntities.Common.Core then the DbContext extension method ApplyChanges is not found anymore.
![image](https://user-images.githubusercontent.com/17270672/34847791-d0788f16-f71c-11e7-9a71-2e7760281e2c.png)

Do you maybe have some hints for me to get it working for EF6 again?

**Comment by tonysneed** [comment]
Why are you referencing EF6? You should instead use this TE package:
[TrackableEntities.EF.Core](https://www.nuget.org/packages/TrackableEntities.EF.Core)

**Comment by ferryferry** [comment]
Hmm okay, but the DbContext instance the Repository.Pattern.Ef6 uses is of type System.Data.Entity (EF6) and not of type Microsoft.EntityFrameworkCore. So when using the TE.EF.Core package you referenced I still have compatibility issues. 
![image](https://user-images.githubusercontent.com/17270672/34905459-3d55904c-f859-11e7-877b-a6b8649a9eda.png)

And ofcourse it sounds logical because the TE.Ef.Core package uses the EF Core as underlying library.

**Comment by ferryferry** [comment]
I Already got it working for just EFCore. I think the only way to fix this issue is to create a separate project for URF.Core. Just because of the dependencies on EFCore / EF6. Because there is no abstraction layer between DbContext (EF6) and DbContext (EFCore). Or maybe @lelong37 and @tonysneed have some ideas to work this out?

**Comment by tonysneed** [comment]
I suggest we create a whole new repo for URF.Core, without any dependency on EF6.  It’s also time to create an org account for urf-net, or something like that.

@lelong37 Thoughts?

**Comment by lelong37** [comment]
Catching up here, @ferryferry, we are porting URF to .NET Core w/ EF Core. Correct me if I'm wrong, you already have URF ported to .NET Core 2.x, .NET Standard 2.x, EF Core 2.x? If so, I think that's good enough for us to review as a PR. This PR could be of added value from a reference implementation or example, all the way up to using some of it for the actual port. 

If your having trouble w/ branching (for now, until we get our URF organization on Github created), simply create a branch and completely delete what's in the new branch, delete everything, commit and publish your empty branch. Finally, copy your port of URF into the new local branch, do an initial commit, and push to the remote branch. Again, just a temporary solution so that we can start reviewing your port ASAP and while we sort out creating an GitHub organization for URF.

**Comment by ferryferry** [comment]
@lelong37 Yes you're right, I already have ported it to .NET Standard. (With dependencies on EFCore 2.x). But I can't find where to create a new branch. I checked it out on the URF repository, but I think I do not have the right permissions to create one. I don't know for sure if I need to be a contributor before I could create one?

Otherwise I can cleanup my own repository and link it, however I think it's easier to have this all at one central place. (for now)

**Comment by tonysneed** [comment]
I think we can pull your branch and use it as a starting point on a new repo we can create under the new org we’re setting up. Then we can accept new PR’s there. We’ll post a link to the repo here, so stay tuned!

**Comment by tonysneed** [comment]
Re-opening, so we can point @ferryferry to the new repo as soon as its' ready.

**Comment by lelong37** [comment]
https://github.com/urfnet/URF.Core beta is released, closing this issue.
