### ISSUE TITLE
Modularize by breaking out ITrackable and IQueryable

### ISSUE THREAD

**Issue by tonysneed** [urfnet/URF.NET#37]
Let's refactor the full URF so that there is a **Core** package that does not depend on ITrackable or IQueryable.  Then create separate packages for those bits that do depend on these interfaces.

**Comment by tonysneed** [comment]
A nice side-effect here is that someone can have an `IRepository<TEntity>` where `TEntity` is not constrained to implement `ITrackable`.  This is required where you have a read-only repository and don't care about updates, for example, with models that are mapped to views in the database.

**Comment by tonysneed** [comment]
We should implement this change first for the v5.1 release and then for the .NET Core version.

**Comment by lelong37** [comment]
This is completed in new https://github.com/urfnet/URF.Core, closing this out.
