### ISSUE TITLE
URF .NET Core

### ISSUE THREAD

**Issue by reader-man** [urfnet/URF.NET#40]
Hi,
 Thanks for the great project.

I was looking for the github url of "URF .NET Core", but could not find it, so can you please provide it.
also, i noticed that:
https://www.nuget.org/packages/URF.Core/1.0.0
is unlisted.

**Comment by tonysneed** [comment]
We’re planning on our own .NET Core port of URF soon, so stay tuned! We will post the link here.

**Comment by tonysneed** [comment]
Update: We've started the .NET Core port of URF and plan to complete it this week.

**Comment by reddy6ue** [comment]
Why not do a .NET standard port? Should work for everything.

**Comment by tonysneed** [comment]
Yes it is a NET Standard port with a dependency on EF Core.

**Comment by tonysneed** [comment]
Here is what we have completed so far: https://github.com/urfnet/URF.Core. Have a look and let us know what you think.

**Comment by lelong37** [comment]
https://github.com/urfnet/URF.Core beta has been released, closing this.
