### ISSUE TITLE
Cosmos DB sql api

### ISSUE THREAD

**Issue by reddy6ue** [urfnet/URF.NET#41]
It looks like a logical next step to support cosmosdb sql api query and associated repositories.

**Comment by tonysneed** [comment]
@lelong37 what do you think?

**Comment by lelong37** [comment]
Hi @reddy6ue , yes, however we'll be only adding Cosmos DB SQL API support for URF.Core version. If you want, just recreate this issue on the https://github.com/urfnet/URF.Core repo, so we can track this request.
