### ISSUE TITLE
Can't find PerRequestLifetimeManager in unity assembly

### ISSUE THREAD

**Issue by imohabdeen** [urfnet/URF.NET#46]
I am using unity framework for entity framework 6 WCF project and i can't find PerRequestLifetimeManager in the assembly. i am using unity version 5.3.2

**Comment by Crazybutch** [comment]
A LifetimeManager that holds onto the instance given to it during the lifetime of a single HTTP request. This lifetime manager enables you to create instances of registered types that behave like singletons within the scope of an HTTP request.

Source: https://msdn.microsoft.com/en-us/library/microsoft.practices.unity.perrequestlifetimemanager%28v=pandp.30%29.aspx?f=255&MSPPError=-2147217396

**Comment by tonysneed** [comment]
@mohamedabdeen This question is answered [here](https://stackoverflow.com/a/12976581).
