### ISSUE TITLE
What's the ETA for URF.NET with .NET Core 2.1?

### ISSUE THREAD

**Issue by IvanFarkas** [urfnet/URF.NET#47]
What's the ETA for **URF.NET** with **.NET Core 2.1**?
**[.NET Core 2.1 RC 1](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/)** is out!

**Comment by tonysneed** [comment]
I'm going to do this next week.  URF has a dependency on Trackable Entities, so I'll be migrating that to 2.1 first and then URF.Core.

**Comment by neozhu** [comment]
Finally, wait until today! thank you very much

**Comment by tonysneed** [comment]
Today is the day .. stay tuned.

**Comment by tonysneed** [comment]
@IvanFarkas @neozhu We released [URF.Core v1 RTM](https://github.com/urfnet/URF.Core/releases/tag/v1.0.0) yesterday.  Cheers.

**Comment by neozhu** [comment]
great job

**Comment by IvanFarkas** [comment]
ditto!
